import type { Component } from "vue";
import {
  Home,
  Upload,
  Folder,
  Share2,
  Wrench,
  Settings,
  User,
  Shield,
  BarChart3,
  Zap,
  FileUp,
  Camera,
  Clipboard,
  Files,
  FolderTree,
  Tag,
  Grid3X3,
  Search,
  List,
  TrendingUp,
  ImagePlus,
  ClipboardList,
  Key,
  Package,
  History,
  Palette,
  Keyboard,
  Bell,
  Server,
  HardDrive,
  BarChart,
  Database,
  Users,
  FileSearch,
  Cpu,
  Activity,
  Sliders,
} from "lucide-vue-next";

export interface MenuItem {
  id: string;
  label: string;
  icon: Component;
  route?: string;
  children?: MenuItem[];
  requiresAuth?: boolean;
  requiresAdmin?: boolean;
  badge?: string | number;
  description?: string;
}

export const menuConfig: MenuItem[] = [
  {
    id: "dashboard",
    label: "首页",
    icon: Home,
    route: "/dashboard",
    requiresAuth: true,
    description: "数据概览和快捷操作",
  },
  {
    id: "upload",
    label: "上传",
    icon: Upload,
    route: "/upload",
    requiresAuth: true,
    description: "上传文件到图床",
    children: [
      {
        id: "upload-quick",
        label: "快速上传",
        icon: FileUp,
        route: "/upload/quick",
        description: "拖拽或选择文件上传",
      },
      {
        id: "upload-screenshot",
        label: "截图上传",
        icon: Camera,
        route: "/upload/screenshot",
        description: "截图并上传",
        badge: "推荐",
      },
      {
        id: "upload-clipboard",
        label: "剪贴板上传",
        icon: Clipboard,
        route: "/upload/clipboard",
        description: "从剪贴板上传图片",
      },
      {
        id: "upload-settings",
        label: "上传设置",
        icon: Settings,
        route: "/upload/settings",
        description: "配置上传默认选项",
      },
    ],
  },
  {
    id: "files",
    label: "我的文件",
    icon: Folder,
    route: "/files",
    requiresAuth: true,
    description: "管理你的文件",
    children: [
      {
        id: "files-all",
        label: "全部文件",
        icon: Files,
        route: "/files/all",
        description: "查看所有上传的文件",
      },
      {
        id: "files-folders",
        label: "文件夹",
        icon: FolderTree,
        route: "/files/folders",
        description: "管理文件夹",
      },
      {
        id: "files-tags",
        label: "标签",
        icon: Tag,
        route: "/files/tags",
        description: "管理标签",
      },
      {
        id: "files-categories",
        label: "分类",
        icon: Grid3X3,
        route: "/files/categories",
        description: "管理分类",
      },
      {
        id: "files-search",
        label: "高级搜索",
        icon: Search,
        route: "/files/search",
        description: "多条件搜索文件",
      },
    ],
  },
  {
    id: "shares",
    label: "分享管理",
    icon: Share2,
    route: "/shares",
    requiresAuth: true,
    description: "管理你的分享链接",
    children: [
      {
        id: "shares-list",
        label: "我的分享",
        icon: List,
        route: "/shares/list",
        description: "查看和管理分享链接",
      },
      {
        id: "shares-stats",
        label: "分享统计",
        icon: TrendingUp,
        route: "/shares/stats",
        description: "分享数据统计",
      },
    ],
  },
  {
    id: "tools",
    label: "工具箱",
    icon: Wrench,
    route: "/tools",
    requiresAuth: true,
    description: "实用工具集合",
    children: [
      {
        id: "tools-image",
        label: "图片处理",
        icon: ImagePlus,
        route: "/tools/image-process",
        description: "压缩、转换、水印、EXIF清理",
      },
      {
        id: "tools-clipboard-history",
        label: "剪贴板历史",
        icon: ClipboardList,
        route: "/tools/clipboard-history",
        description: "查看剪贴板历史记录",
      },
      {
        id: "tools-api",
        label: "API 管理",
        icon: Key,
        route: "/tools/api",
        description: "管理 API Key",
      },
      {
        id: "tools-batch",
        label: "批量操作",
        icon: Package,
        route: "/tools/batch",
        description: "批量上传、下载、修改",
      },
      {
        id: "tools-history",
        label: "上传历史",
        icon: History,
        route: "/tools/history",
        description: "查看本地上传历史",
      },
    ],
  },
  {
    id: "settings",
    label: "设置",
    icon: Settings,
    route: "/settings",
    requiresAuth: true,
    description: "应用程序设置",
    children: [
      {
        id: "settings-appearance",
        label: "外观设置",
        icon: Palette,
        route: "/settings/appearance",
        description: "主题、语言、字体",
      },
      {
        id: "settings-shortcuts",
        label: "快捷键",
        icon: Keyboard,
        route: "/settings/shortcuts",
        description: "自定义快捷键",
      },
      {
        id: "settings-notifications",
        label: "通知",
        icon: Bell,
        route: "/settings/notifications",
        description: "通知偏好设置",
      },
      {
        id: "settings-server",
        label: "服务器",
        icon: Server,
        route: "/settings/server",
        description: "服务器和账号设置",
      },
      {
        id: "settings-upload-defaults",
        label: "上传默认配置",
        icon: FileUp,
        route: "/settings/upload-defaults",
        description: "配置默认上传选项",
      },
      {
        id: "settings-cache",
        label: "本地缓存",
        icon: HardDrive,
        route: "/settings/cache",
        description: "缓存管理",
      },
    ],
  },
  {
    id: "profile",
    label: "个人中心",
    icon: User,
    route: "/profile",
    requiresAuth: true,
    description: "个人信息和统计",
    children: [
      {
        id: "profile-stats",
        label: "我的统计",
        icon: BarChart,
        route: "/profile/stats",
        description: "查看个人数据统计",
      },
      {
        id: "profile-security",
        label: "账号安全",
        icon: Shield,
        route: "/profile/security",
        description: "密码、邮箱、两步验证",
      },
      {
        id: "profile-storage",
        label: "存储空间",
        icon: Database,
        route: "/profile/storage",
        description: "存储空间管理",
      },
    ],
  },
  {
    id: "admin",
    label: "管理中心",
    icon: Shield,
    route: "/admin",
    requiresAuth: true,
    requiresAdmin: true,
    description: "系统管理功能",
    children: [
      {
        id: "admin-users",
        label: "用户管理",
        icon: Users,
        route: "/admin/users",
        description: "管理用户",
      },
      {
        id: "admin-files",
        label: "文件审核",
        icon: FileSearch,
        route: "/admin/files",
        description: "审核和管理文件",
      },
      {
        id: "admin-ai",
        label: "AI 管理",
        icon: Cpu,
        route: "/admin/ai",
        description: "管理 AI 服务",
      },
      {
        id: "admin-monitor",
        label: "系统监控",
        icon: Activity,
        route: "/admin/monitor",
        description: "监控系统状态",
      },
      {
        id: "admin-settings",
        label: "系统设置",
        icon: Sliders,
        route: "/admin/settings",
        description: "系统配置",
      },
    ],
  },
];
